import GridSVG from "@/components/SVG/GridSVG";

export const metadata = {
	title: "Signup page",
	description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
	return (
		<div className="min-h-screen w-full relative flex justify-center items-center">
			<main className="z-10 flex justify-center items-center h-fit p-5 relative my-auto">
				{children}
			</main>


			{/* Background */}
			<div className="z-0 absolute top-0 left-1/2 translate-x-[-50%] h-full overflow-hidden w-screen">
				{/* Background yellow gradient */}
				<div
					className="pointer-events-none
                          w-1/2 aspect-square min-w-[1250px]
                          absolute top-[-70%] right-1/2
                          bg-[#ecf15e41] blur-[150px] rounded-full
                          translate-x-1/2 rotate-45"
				></div>

				{/* Grid */}
				<GridSVG className="z--10 object-contain right-1/2 translate-x-[50%] absolute"/>
				
        		{/* Black filters */}
				<div className="absolute w-full h-full bg-gradient-to-t from-background via-background via-70%"></div>
				<div className="absolute w-full h-full bg-gradient-to-r from-background to-transparent via-transparent via-30%"></div>
				<div className="absolute w-full h-full bg-gradient-to-l from-background to-transparent via-transparent via-30%"></div>

			</div>
		</div>
	);
}
