export const metadata = {
  title: "Signup page",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
      <div className="bg-neutral-950 h-screen w-full">

        <main className="flex justify-center items-center h-full p-5">
            {children}
        </main>



        {/* Background yellow gradient */}
        <div className="z-0
                        w-1/2 aspect-square
                        absolute top-[-70%] right-1/2
                        bg-[#ecf15e4d] blur-[250px] rounded-full
                        translate-x-1/2 rotate-45">
        </div>
        {/* <div className="z-10 bg-grid-3d absolute inset-0 w-full h-1/2"></div> */}
      </div>
  );
}
