import GridSVG from "@/components/SVG/GridSVG";

export const metadata = {
  title: "Signup page",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
      <div className="h-screen w-full">

        <main className="flex justify-center items-center h-full p-5">
            {children}
        </main>



        {/* Background yellow gradient */}
        <div className="z--10
                        pointer-events-none
                        w-1/2 aspect-square
                        absolute top-[-70%] right-1/2
                        bg-[#ecf15e4d] blur-[250px] rounded-full
                        translate-x-1/2 rotate-45">
        </div>
        <div className="absolute top-0 left-1/2 translate-x-[-50%]">
          <div className="z-10 w-full h-full bg-gradient-to-t from-background to-transparent"></div>
          <GridSVG className="z-0"/>

        </div>
      </div>
  );
}
